NewUserId="userName"
NewUserMail="userEmail"
NewUserRole="userRole"
AddUserButton="//button[contains(text(),'Add User')]"
MainPageHeader="//h5[contains(text(),'Add User (Demo)')]"
userData="//td[contains(text(),'"
EditUserData="/following-sibling::td[3]/div/button[1]"
DeleteButton="/following-sibling::td[3]/div/button[2]"
EditUserHeader="//h5[contains(text(),'Edit User')]"
EditUserName="(//input[@id='userName'])[2]"
EditUserMail="(//input[@id='userEmail'])[2]"
EditUserRole="(//input[@id='userRole'])[2]"
EditUser="//button[contains(text(),'Edit User')]"